import { MockImage } from "@root/assets";
export const TableMockDataasds = [
  {
    id: "098134NN",
    name: "Rompi Berkancing",
    image: MockImage,
    price: "$400.98",
    stock: "234",
    statistics: "",
    active: "",
  },
  {
    id: "088134NT",
    name: "Blazzer assorted pocket",
    image: MockImage,
    price: "$550.75",
    stock: "570",
    statistics: "",
    active: "",
  },
  {
    id: "088134NT",
    name: "Pattern top with knot",
    image: MockImage,
    price: "$210.98",
    stock: "89",
    statistics: "",
    active: "",
  },
  {
    id: "088134NT",
    name: "Basic Hoodie - blue",
    image: MockImage,
    price: "$149.99",
    stock: "989",
    statistics: "",
    active: "",
  },
  {
    id: "088134NT",
    name: "Tight plain blazer",
    image: MockImage,
    price: "$276.99",
    stock: "876",
    statistics: "",
    active: "",
  },
];
export const TableMockData = [
  {
    name: "Menu 1",
    // price: "$400.98",
    // stock: "234",
    // statistics: "",
    // active: "",
    item: [
      {
        id: "098134NN",
        name: "Rompi Berkancing",
        image: MockImage,
        price: "$400.98",
        stock: "234",
        statistics: "",
        active: "",
      },
      {
        id: "088134NT",
        name: "Blazzer assorted pocket",
        image: MockImage,
        price: "$550.75",
        stock: "570",
        statistics: "",
        active: "",
      },
    ],
  },
  {
    name: "Menu 1",
    // price: "$400.98",
    // stock: "234",
    // statistics: "",
    // active: "",
    item: [
      {
        id: "098134NN",
        name: "Rompi Berkancing",
        image: MockImage,
        price: "$400.98",
        stock: "234",
        statistics: "",
        active: "",
      },
      {
        id: "088134NT",
        name: "Blazzer assorted pocket",
        image: MockImage,
        price: "$550.75",
        stock: "570",
        statistics: "",
        active: "",
      },
    ],
  },
  {
    name: "Menu 1",
    // price: "$400.98",
    // stock: "234",
    // statistics: "",
    // active: "",
    item: [
      {
        id: "098134NN",
        name: "Rompi Berkancing",
        image: MockImage,
        price: "$400.98",
        stock: "234",
        statistics: "",
        active: "",
      },
      {
        id: "088134NT",
        name: "Blazzer assorted pocket",
        image: MockImage,
        price: "$550.75",
        stock: "570",
        statistics: "",
        active: "",
      },
    ],
  },
];
// export const TableMockData: any[] = [
//   {
//     category: "Foo",
//     total: 300,
//     expenses: [
//       { name: "Bar", value: 100 },
//       { name: "Baz", value: 200 },
//     ],
//   },
//   {
//     category: "Transport",
//     total: 300,
//     expenses: [
//       { name: "Car", value: 100 },
//       { name: "Car", value: 100 },
//       { name: "Bike", value: 200 },
//     ],
//   },
//   { category: "Test", total: 0, expenses: [] },
// ];
