import {
  navSettingIcon,
  navDiscountIcon,
  navOrderIcon,
  navProductIcon,
  navCustomerIcon,
  navAnalyticsIcon,
  navMarketingIcon,
  navIntegrationIcon,
  navMystoreIcon,
  navHelpIcon,
  navHomeIcon,
  navFilledSettingIcon,
  navFilledProductIcon,
  navFilledOrdersIcon,
  navFilledMarketingIcon,
  navFilledIntegrationIcon,
  navFilledHomeIcon,
  navFilledHelpIcon,
  navFilledDiscountIcon,
  navFilledCustomerIcon,
  navFilledAnalyticsIcon,
  navFilledMyStoreIcon,
} from "@root/assets";
// import {PiShoppingCartLight,PiBriefcaseLight,IoPersonOutline} from "react-icons/"
export const NavData = [
  {
    id: 1,
    name: "Dashboard",
    filledIcon: navFilledHomeIcon,
    icon: navHomeIcon,
    link: "#",
  },
  {
    id: 2,
    name: "Bookings",
    filledIcon: navFilledOrdersIcon,
    icon: navOrderIcon,
    link: "bookings",
  },
  {
    id: 3,
    name: "Orders",
    filledIcon: navFilledOrdersIcon,
    icon: navOrderIcon,
    link: "",
  },
  {
    id: 4,
    name: "Products",
    filledIcon: navFilledProductIcon,
    icon: navProductIcon,
    link: "products",
  },
  {
    id: 5,
    name: "Customers",
    filledIcon: navFilledCustomerIcon,
    icon: navCustomerIcon,
    link: "",
  },
  {
    id: 6,
    name: "Analytics",
    filledIcon: navFilledAnalyticsIcon,
    icon: navAnalyticsIcon,
    link: "",
  },
  {
    id: 7,
    name: "Marketing",
    filledIcon: navFilledMarketingIcon,
    icon: navMarketingIcon,
    link: "",
  },
  {
    id: 8,
    name: "Integrations",
    filledIcon: navFilledIntegrationIcon,
    icon: navIntegrationIcon,
    link: "",
  },
  {
    id: 9,
    name: "My Store",
    filledIcon: navFilledMyStoreIcon,
    icon: navMystoreIcon,
    link: "",
  },
  {
    id: 10,
    name: "Discounts",
    filledIcon: navFilledDiscountIcon,
    icon: navDiscountIcon,
    link: "",
  },
  {
    id: 11,
    name: "Settings",
    filledIcon: navFilledSettingIcon,
    icon: navSettingIcon,
    link: "",
  },
  {
    id: 12,
    name: "Get Help",
    filledIcon: navFilledHelpIcon,
    icon: navHelpIcon,
    link: "",
  },
];
