import { MockImage } from "@root/assets";

export const BookingMockData = [
  {
    date: "Apr 24, 2022",
    Customer: "Chieko Chute",
    Payment: "Paid",
    Status: "Unfulfilled",
    id: "098134NN",
    name: "Vest Hoddie",
    image: MockImage,
    price: "$400.98",
  },
  {
    date: "Apr 24, 2022",
    Customer: "Chieko Chute",
    Payment: "Unpaid",
    Status: "Completed",
    id: "088134NT",
    name: "Blazzer assorted pocket",
    image: MockImage,
    price: "$550.75",
  },
  {
    date: "Apr 24, 2022",
    Customer: "Chieko Chute",
    Payment: "Unpaid",
    Status: "Unfulfilled",
    id: "088134NT",
    name: "Pattern top with knot",
    image: MockImage,
    price: "$210.98",
  },
  {
    date: "Apr 24, 2022",
    Customer: "Pedro Huard",
    Payment: "Paid",
    Status: "Unfulfilled",
    id: "088134NT",
    name: "Basic Hoodie - blue",
    image: MockImage,
    price: "$149.99",
  },
  {
    date: "Apr 24, 2022",
    Customer: "Augustina Midgett",
    Payment: "Paid",
    Status: "Shipping",
    id: "088134NT",
    name: "Tight plain blazer",
    image: MockImage,
    price: "$276.99",
  },
  {
    date: "Apr 24, 2022",
    Customer: "Chieko Chute",
    Payment: "Paid",
    Status: "Shipping",
    id: "088134NT",
    name: "Tight plain blazer",
    image: MockImage,
    price: "$276.99",
  },
];
